services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    ports:
      - "8889:8889"
      - "8554:8554"
      - "8189:8189/udp"
    volumes:
      - ./streaming/mediamtx.yml:/mediamtx.yml
    environment:
      - MTX_WEBRTCADDITIONALHOSTS=${HOST_IP}
    restart: unless-stopped

  gstreamer:
    build:
      context: ./streaming
      dockerfile: Dockerfile
    devices:
      - ${VIDEO_DEVICE}:/dev/video0
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/snd:/dev/snd
    environment:
      - WIDTH=${WIDTH:-1920}
      - HEIGHT=${HEIGHT:-1080}
      - BITRATE=${BITRATE:-12000}
      - AUDIO_DEVICE=${AUDIO_DEVICE}
      - SCREENSHOT_CACHE_FPS=${SCREENSHOT_CACHE_FPS:-10}
      - SCREENSHOT_STREAM_PORT=${SCREENSHOT_STREAM_PORT:-9001}
    restart: unless-stopped
    depends_on:
      - mediamtx

  nxmc:
    build: ./nxmc
    ports:
      - "9000:9000"
    devices:
      - ${SERIAL_DEVICE}:/dev/ttyUSB0
    environment:
      - WIDTH=${WIDTH:-1920}
      - HEIGHT=${HEIGHT:-1080}
      - BITRATE=${BITRATE:-12000}
      - AUDIO_DEVICE=${AUDIO_DEVICE}
      - RTSP_HOST=mediamtx
      - SCREENSHOT_CACHE_FPS=${SCREENSHOT_CACHE_FPS:-10}
      - SCREENSHOT_STREAM_PORT=${SCREENSHOT_STREAM_PORT:-9001}
      - SCREENSHOT_STREAM_ADDR=gstreamer:${SCREENSHOT_STREAM_PORT:-9001}
    restart: unless-stopped
    depends_on:
      - mediamtx
